import React from "react";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { FileText, Clipboard, Scale } from "lucide-react";

export default function TermsPage() {
  return (
    <>
      <Navbar />
      
      <section className="bg-slate-950 py-12 text-center text-white relative">
        <div className="absolute inset-0 opacity-15 bg-[radial-gradient(#0B7A3B_1px,transparent_1px)] [background-size:16px_16px]"></div>
        <div className="relative max-w-7xl mx-auto px-4 space-y-2">
          <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight">Terms & Conditions</h1>
          <p className="text-slate-400 text-xs sm:text-sm">Last updated: June 3, 2026</p>
        </div>
      </section>

      <section className="py-12 bg-background text-sm text-muted-foreground leading-relaxed">
        <div className="max-w-4xl mx-auto px-4 space-y-6">
          <div className="flex gap-3 items-start bg-slate-50 dark:bg-slate-900/30 p-5 rounded-lg border">
            <Scale className="text-primary shrink-0 w-6 h-6 mt-0.5" />
            <div className="space-y-1">
              <h3 className="font-bold text-slate-800 dark:text-slate-200">System Use Guidelines</h3>
              <p>
                By using the Delhi Public School, Damanjodi ERP Portal and official website, you agree to comply with standard code of conduct rules, use secure passwords, and log out after academic updates.
              </p>
            </div>
          </div>

          <div className="space-y-3">
            <h3 className="font-bold text-slate-800 dark:text-slate-200 text-base">1. ERP Credentials Security</h3>
            <p>
              Users are responsible for maintaining the confidentiality of their login emails and passwords. Sharing student or teacher access credentials with third-party utilities is strictly prohibited.
            </p>
          </div>

          <div className="space-y-3">
            <h3 className="font-bold text-slate-800 dark:text-slate-200 text-base">2. Fee Payment & Refunds</h3>
            <p>
              Online payment transactions must use authenticated cards or UPI links. Dues collections and admission fees are non-refundable. Receipt printouts generated by the portal are official records.
            </p>
          </div>

          <div className="space-y-3">
            <h3 className="font-bold text-slate-800 dark:text-slate-200 text-base">3. Content Intellectual Property</h3>
            <p>
              The school crest, design layout, course syllabus files, and newsletters are protected by copyright. Unauthorized replication or extraction of databases is subject to CBSE legal frameworks.
            </p>
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
}
